# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        carre: #nom du filtre
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
        echelle: #nom du filtre
            quality: 85
            filters:
                scale:
                    dim: [250, 250]
        thumb: #nom du filtre
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound
        medium: #nom du filtre
            quality: 80
            filters:
                upscale:
                    min: [600, 400]
                thumbnail:
                    size: [600, 400]
                    mode: outbound
        large: #nom du filtre
            quality: 80
            filters:
                upscale:
                    size: [800, 600]
                    mode: outbound
        big: #nom du filtre
            quality: 80
            filters:
                upscale:
                    min: [800, 400]
                thumbnail:
                    size: [800, 400]
                    mode: outbound
#                watermark:
#                    image:
#                    size: 1
#                    position: bottomright